Algoritmo "semnome"

Var
mat:vetor[1..3,1..3] de inteiro
i,j: inteiro



Inicio
para i de 1 ate 3 passo 1 faca
          para j de 1  ate 3 passo 1 faca
               escreva("elemento",i,",",j ,":")
               leia(mat[i,j])
          fimpara
fimpara
para i de 1 ate 3 passo 1 faca
     para j de 1 ate 3 passo 1 faca
            escreva(mat[i,j])
            fimpara
            escreval
     fimpara
Fimalgoritmo