Algoritmo "semnome"
// Disciplina   : [Linguagem e Lógica de Programação]
// Professor   : Antonio Carlos Nicolodi 
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : Nome do(a) aluno(a)
// Data atual  : 31/08/2021
Var
 num:inteiro
 
Inicio
      escreval ("Digite um valor entre 10 e 20:")
      leia(num)
          se(num>10) e (num<20) entao
      escreval ("valor correto!")
               senao escreval("valor incorreto!")
     fimse

Fimalgoritmo