Algoritmo "Estudando denovo"
// Disciplina   : [Linguagem e Lógica de Programação]
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : Nome do(a) aluno(a)
// Data atual  : 01/12/2023
Var
h,b,a: real
Inicio
      escreval("Digite o valor da base: ")
      leia(b)
      escreval("Digite o valor da altura: ")
      leia(h)
      a <- b * h / 2
      escreval("A área do triangulo é:",a)



Fimalgoritmo