Algoritmo "Estudando denovo"
// Disciplina   : [Linguagem e Lógica de Programação]
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : Nome do(a) aluno(a)
// Data atual  : 01/12/2023
Var
y: inteiro
x:real
Inicio

      y <- 15 mod 13
      escreval(y)
      y <- 15 % 13
      escreval(y)
      y <- 130 div 10
      escreval(y)
      y <- 5 mod 4
      escreval(y)
      x <- 2^4
      escreval(x)


Fimalgoritmo