Algoritmo "Estudando denovo"
// Disciplina   : [Linguagem e Lógica de Programação]
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : Nome do(a) aluno(a)
// Data atual  : 01/12/2023
Var

x:real
y: real
z:caractere
w:inteiro

Inicio

x <- raizq (9) + raizq(100)
escreval(x)

x <- 12 * pi
escreval(x)

y <- randi(20)
escreval(y)

z <- maiusc("brasil")
escreval(z)

w <- compr("casa")
escreval(w)


Fimalgoritmo